apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buttercup-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/afc-buttercup.git
    targetRevision: main
    path: deployment/k8s/openshift
    kustomize:
      enableHelm: true
  destination:
    server: https://kubernetes.default.svc
    namespace: buttercup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
