apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: buttercup

resources:
  - ../namespace.yaml

helmCharts:
  - name: buttercup
    includeCRDs: true
    releaseName: buttercup
    valuesFile: values-openshift-airgap.yaml
    repo: file://../..
