use std::path::Path;
use std::process::{Command, ExitCode, Stdio};

use clap::{Parser, Subcommand};

#[derive(Debug, Parser)]
#[command(
    name = "buttercup-dev",
    version,
    about = "Simple Rust CLI for local Buttercup developer workflows"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    /// Start the local docker compose stack.
    Up {
        /// Optional docker compose profile, e.g. graphdb.
        #[arg(long)]
        profile: Option<String>,
    },
    /// Stop and clean up the local docker compose stack.
    Down,
    /// Start CRS services via deployment/Makefile.
    DeployUp,
    /// Stop CRS services via deployment/Makefile.
    DeployDown,
    /// Send the sample task through the local orchestrator script.
    Task,
    /// Send SARIF for an existing task id.
    SendSarif {
        /// Task ID generated by task submission.
        task_id: String,
    },
    /// Simulate unscored round challenge submission.
    Challenge,
}

fn main() -> ExitCode {
    let cli = Cli::parse();

    let result = match cli.command {
        Commands::Up { profile } => run_compose_up(profile.as_deref()),
        Commands::Down => run_from_repo("docker", &["compose", "down", "--remove-orphans"]),
        Commands::DeployUp => run_from_repo("make", &["-C", "deployment", "up"]),
        Commands::DeployDown => run_from_repo("make", &["-C", "deployment", "down"]),
        Commands::Task => run_from_repo("./orchestrator/scripts/task_crs.sh", &[]),
        Commands::SendSarif { task_id } => {
            run_from_repo("./orchestrator/scripts/send_sarif.sh", &[task_id.as_str()])
        }
        Commands::Challenge => run_from_repo("./orchestrator/scripts/challenge.sh", &[]),
    };

    match result {
        Ok(code) => ExitCode::from(code as u8),
        Err(message) => {
            eprintln!("error: {message}");
            ExitCode::from(1)
        }
    }
}

fn run_compose_up(profile: Option<&str>) -> Result<i32, String> {
    let mut args = vec!["compose"];

    if let Some(profile_name) = profile {
        args.push("--profile");
        args.push(profile_name);
    }

    args.extend(["up", "-d"]);
    run_from_repo("docker", &args)
}

fn run_from_repo(command: &str, args: &[&str]) -> Result<i32, String> {
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("failed to compute repository root")?;

    let status = Command::new(command)
        .args(args)
        .current_dir(repo_root)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .map_err(|error| format!("failed to execute `{command}`: {error}"))?;

    Ok(status.code().unwrap_or(1))
}
